const entreprises = [
  {
    id: 1,
    nom: "ENGIE",
    secteur: "Energie",
    adresse: "123 Rue de la Tech, Paris",
    email: "contact@techsolutions.fr",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Logo-engie.svg/2445px-Logo-engie.svg.png",
    siteWeb: "https://www.techsolutions.fr",
    nombreEmployes: 250,
    alert: 3,
  },
  {
    id: 2,
    nom: "LVMH",
    secteur: "Retail - Luxe",
    adresse: "123 Rue de la Tech, Paris",
    email: "contact@techsolutions.fr",
    img: "https://images.prismic.io/clublvmh-actionnaires/8a3feaf2-7a93-451c-a90f-462a3f888616_LVMH_Logotype_Simple_N.PNG?auto=compress,format",
    siteWeb: "https://www.techsolutions.fr",
    nombreEmployes: 250,
    alert: 1,
  },
  {
    id: 3,
    nom: "TotalEnergies",
    secteur: "Technologie",
    adresse: "123 Rue de la Tech, Paris",
    email: "contact@techsolutions.fr",
    img: "https://upload.wikimedia.org/wikipedia/fr/thumb/d/dd/TOTAL_SA_logo.svg/2501px-TOTAL_SA_logo.svg.png",
    siteWeb: "https://www.techsolutions.fr",
    nombreEmployes: 250,
    alert: 5,
  },
  {
    id: 4,
    nom: "ENGIE",
    secteur: "Energie",
    adresse: "123 Rue de la Tech, Paris",
    email: "contact@techsolutions.fr",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Logo-engie.svg/2445px-Logo-engie.svg.png",
    siteWeb: "https://www.techsolutions.fr",
    nombreEmployes: 250,
    alert: 3,
  },
  {
    id: 5,
    nom: "LVMH",
    secteur: "Retail - Luxe",
    adresse: "123 Rue de la Tech, Paris",
    email: "contact@techsolutions.fr",
    img: "https://images.prismic.io/clublvmh-actionnaires/8a3feaf2-7a93-451c-a90f-462a3f888616_LVMH_Logotype_Simple_N.PNG?auto=compress,format",
    siteWeb: "https://www.techsolutions.fr",
    nombreEmployes: 250,
    alert: 1,
  },
  {
    id: 6,
    nom: "TotalEnergies",
    secteur: "Energie",
    adresse: "123 Rue de la Tech, Paris",
    email: "contact@techsolutions.fr",
    img: "https://upload.wikimedia.org/wikipedia/fr/thumb/d/dd/TOTAL_SA_logo.svg/2501px-TOTAL_SA_logo.svg.png",
    siteWeb: "https://www.techsolutions.fr",
    nombreEmployes: 250,
    alert: 5,
  },
];

export default entreprises;
